package model

// Item definitions are authored here. IDs are stable content and save contracts.
var itemDefinitions = validateItemDefinitions(map[string]ItemDefinition{
	"ironSword": {
		Name:          "Iron Sword",
		Type:          "weapon",
		RenderModel:   "ironSword",
		EquipmentSlot: SlotWeapon,
		CombatStats: &ItemCombatStats{
			MinDamage:        6,
			MaxDamage:        10,
			AccuracyBonus:    5,
			CritBonus:        0.05,
			Range:            1,
			AttackSpeedTicks: 2,
			AttackMethod:     AttackMethodMelee,
		},
	},
	"woodcuttingAxe": {
		Name:          "Woodcutting Axe",
		Type:          "axe",
		RenderModel:   "woodcuttingAxe",
		EquipmentSlot: SlotWeapon,
		CombatStats: &ItemCombatStats{
			MinDamage:        3,
			MaxDamage:        5,
			AccuracyBonus:    2,
			CritBonus:        0.02,
			Range:            1,
			AttackSpeedTicks: 3,
			AttackMethod:     AttackMethodMelee,
		},
	},
	"fishingRod": {
		Name:          "Fishing Rod",
		Type:          "fishingRod",
		RenderModel:   "fishingRod",
		EquipmentSlot: SlotWeapon,
	},
	"woodenBow": {
		Name:          "Wooden Bow",
		Type:          "weapon",
		RenderModel:   "woodenBow",
		EquipmentSlot: SlotWeapon,
		CombatStats: &ItemCombatStats{
			MinDamage:        4,
			MaxDamage:        7,
			AccuracyBonus:    6,
			CritBonus:        0.03,
			Range:            3,
			AttackSpeedTicks: 3,
			AttackMethod:     AttackMethodRanged,
			WindUpTicks:      2,
			TravelTicks:      1,
			ProjectileType:   "arrow",
		},
	},
	"magicStaff": {
		Name:          "Magic Staff",
		Type:          "weapon",
		RenderModel:   "magicStaff",
		EquipmentSlot: SlotWeapon,
		CombatStats: &ItemCombatStats{
			MinDamage:        5,
			MaxDamage:        9,
			AccuracyBonus:    4,
			CritBonus:        0.08,
			Range:            4,
			AttackSpeedTicks: 3,
			AttackMethod:     AttackMethodMagic,
			WindUpTicks:      2,
			TravelTicks:      1,
			ProjectileType:   "magicBolt",
		},
	},
	"leatherHelmet": {
		Name:          "Leather Helmet",
		Type:          "armor",
		RenderModel:   "leatherHelmet",
		EquipmentSlot: SlotHead,
		CombatStats: &ItemCombatStats{
			ArmorBonus: 2,
			Range:      1,
		},
	},
	"chainmailChestplate": {
		Name:          "Chainmail Chestplate",
		Type:          "armor",
		RenderModel:   "chainmailChestplate",
		EquipmentSlot: SlotChest,
		CombatStats: &ItemCombatStats{
			ArmorBonus: 4,
			Range:      1,
		},
	},
	"ironLeggings": {
		Name:          "Iron Leggings",
		Type:          "armor",
		RenderModel:   "ironLeggings",
		EquipmentSlot: SlotLegs,
		CombatStats: &ItemCombatStats{
			ArmorBonus: 3,
			Range:      1,
		},
	},
	"leatherBoots": {
		Name:          "Leather Boots",
		Type:          "armor",
		RenderModel:   "leatherBoots",
		EquipmentSlot: SlotFeet,
		CombatStats: &ItemCombatStats{
			ArmorBonus: 1,
			Range:      1,
		},
	},
	"woodenShield": {
		Name:          "Wooden Shield",
		Type:          "shield",
		RenderModel:   "woodenShield",
		EquipmentSlot: SlotOffhand,
		CombatStats: &ItemCombatStats{
			ArmorBonus: 3,
			Range:      1,
		},
	},
	"healthPotion": {
		Name:        "Health Potion",
		Type:        "consumable",
		RenderModel: "healthPotion",
	},
	"bread": {
		Name:        "Bread",
		Type:        "consumable",
		RenderModel: "bread",
	},
	"apple": {
		Name:        "Apple",
		Type:        "consumable",
		RenderModel: "apple",
	},
	"ironOre": {
		Name:        "Iron Ore",
		Type:        "material",
		RenderModel: "ironOre",
	},
	"wood": {
		Name:        "Wood",
		Type:        "material",
		RenderModel: "wood",
	},
	"logs": {
		Name:        "Logs",
		Type:        "material",
		RenderModel: "logs",
	},
	"stone": {
		Name:        "Stone",
		Type:        "material",
		RenderModel: "stone",
	},
	"arrow": {
		Name:        "Arrow",
		Type:        "arrow",
		RenderModel: "arrow",
		Stackable:   true,
	},
	"mysteriousKey": {
		Name:        "Mysterious Key",
		Type:        "quest",
		RenderModel: "mysteriousKey",
	},
	"ancientScroll": {
		Name:        "Ancient Scroll",
		Type:        "quest",
		RenderModel: "ancientScroll",
	},
	"gold": {
		Name:        "Gold",
		Type:        "gold",
		RenderModel: "gold",
		Stackable:   true,
	},
	"rawFish": {
		Name:        "Raw Fish",
		Type:        "fish",
		RenderModel: "fish",
	},
})
